spring:
  cloud:
    gateway:
      routes:
      - id: service-products
        uri: lb://service-products
        predicates:
          - Path=/api/products/**
#          - Header=token, \d+
#          - Header=Content-Type, application/json
#          - Method=GET, POST
#          - Query=color
#          - Cookie=color, azul
        filters:
          - StripPrefix=2 
          - CookieExample=Mensaje personalizado,usuario,FacundoCenteno
      - id: service-items
        uri: lb://service-items
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2
          - AddRequestHeader=token-request, 123456
          - AddResponseHeader=token-response, 123789
          - SetResponseHeader=Content-Type, text/plain
          - AddRequestParameter=name, facundo
        
          

          
      